<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\Culture.json" Link="Culture.json" />
    <None Include="..\Culture.json" Link="Culture.json" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\..\src\Arkheide.Essential.Culture.Wpf\Arkheide.Essential.Culture.Wpf.csproj" />
    <ProjectReference Include="..\..\src\Arkheide.Essential.Culture.Generator\Arkheide.Essential.Culture.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
