<Project>
  <Target
    Name="ArkheideEssentialCulturePrepareDefaultDocument"
    BeforeTargets="PrepareForBuild;GenerateMSBuildEditorConfigFile"
    Condition="'$(ArkheideEssentialCultureAutoInclude)' != 'false'">
    <PropertyGroup>
      <_ArkheideEssentialCultureDefaultDocument>$(MSBuildProjectDirectory)\Culture.json</_ArkheideEssentialCultureDefaultDocument>
    </PropertyGroup>

    <ItemGroup>
      <_ArkheideEssentialCultureExplicitDocument
        Include="@(AdditionalFiles)"
        Condition="'%(AdditionalFiles.Filename)%(AdditionalFiles.Extension)' == 'Culture.json'" />
      <_ArkheideEssentialCultureExplicitRootDocument
        Include="@(_ArkheideEssentialCultureExplicitDocument)"
        Condition="'%(_ArkheideEssentialCultureExplicitDocument.FullPath)' == '$(_ArkheideEssentialCultureDefaultDocument)'" />
      <_ArkheideEssentialCultureExistingContent
        Include="@(Content)"
        Condition="'%(Content.FullPath)' == '$(_ArkheideEssentialCultureDefaultDocument)'" />
    </ItemGroup>

    <Copy
      SourceFiles="$(MSBuildThisFileDirectory)Culture.template.json"
      DestinationFiles="$(_ArkheideEssentialCultureDefaultDocument)"
      Condition="'$(ArkheideEssentialCultureAutoCreate)' != 'false' and '@(_ArkheideEssentialCultureExplicitDocument)' == '' and !Exists('$(_ArkheideEssentialCultureDefaultDocument)')" />

    <ItemGroup Condition="Exists('$(_ArkheideEssentialCultureDefaultDocument)') and ('@(_ArkheideEssentialCultureExplicitDocument)' == '' or '@(_ArkheideEssentialCultureExplicitRootDocument)' != '')">
      <AdditionalFiles
        Include="$(_ArkheideEssentialCultureDefaultDocument)"
        Condition="'@(_ArkheideEssentialCultureExplicitDocument)' == ''" />
      <Content
        Update="@(Content)"
        CopyToOutputDirectory="PreserveNewest"
        CopyToPublishDirectory="PreserveNewest"
        Condition="'%(Content.FullPath)' == '$(_ArkheideEssentialCultureDefaultDocument)'" />
      <Content
        Include="$(_ArkheideEssentialCultureDefaultDocument)"
        Link="Culture.json"
        CopyToOutputDirectory="PreserveNewest"
        CopyToPublishDirectory="PreserveNewest"
        Condition="'@(_ArkheideEssentialCultureExistingContent)' == ''" />
    </ItemGroup>
  </Target>

</Project>
