<Project>
  <Target
    Name="ArkheideEssentialCulturePrepareDefaultDocument"
    BeforeTargets="GenerateMSBuildEditorConfigFile"
    Condition="'$(ArkheideEssentialCultureAutoInclude)' != 'false' and Exists('$(MSBuildProjectDirectory)\Culture.json')">
    <ItemGroup>
      <_ArkheideEssentialCultureExplicitDocument
        Include="@(AdditionalFiles)"
        Condition="'%(AdditionalFiles.Filename)%(AdditionalFiles.Extension)' == 'Culture.json'" />
      <AdditionalFiles
        Include="$(MSBuildProjectDirectory)\Culture.json"
        Condition="'@(_ArkheideEssentialCultureExplicitDocument)' == ''" />
    </ItemGroup>
  </Target>

  <Target
    Name="ArkheideEssentialCultureCopyDefaultDocumentToOutput"
    AfterTargets="Build"
    Condition="'$(ArkheideEssentialCultureAutoInclude)' != 'false' and Exists('$(MSBuildProjectDirectory)\Culture.json')">
    <Copy
      SourceFiles="$(MSBuildProjectDirectory)\Culture.json"
      DestinationFiles="$(TargetDir)Culture.json"
      SkipUnchangedFiles="true" />
  </Target>

  <Target
    Name="ArkheideEssentialCultureCopyDefaultDocumentToPublish"
    AfterTargets="Publish"
    Condition="'$(ArkheideEssentialCultureAutoInclude)' != 'false' and Exists('$(MSBuildProjectDirectory)\Culture.json')">
    <Copy
      SourceFiles="$(MSBuildProjectDirectory)\Culture.json"
      DestinationFiles="$(PublishDir)Culture.json"
      SkipUnchangedFiles="true" />
  </Target>
</Project>
