<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <LangKeyNamespace>ArkheideSystem.LangKey.Demo.ConsoleApp.Generated</LangKeyNamespace>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\LangKey.json" Link="LangKey.json" />
    <None Include="..\LangKey.json" Link="LangKey.json" CopyToOutputDirectory="PreserveNewest" />
    <CompilerVisibleProperty Include="LangKeyNamespace" />
    <ProjectReference Include="..\..\src\LangKey\LangKey.csproj" />
    <ProjectReference Include="..\..\src\LangKey.Generator\LangKey.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
