<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ArkheideSystem.Essential.Culture.Demo.Wpf</RootNamespace>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\Culture.json" Link="Culture.json" />
    <None Include="..\Culture.json" Link="Culture.json" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Arkheide.Essential.Culture.Wpf" Version="$(VersionPrefix)" Condition="'$(UseLocalCulture)' != 'true'" />
    <ProjectReference Include="..\..\src\Essential.Culture.Wpf\Essential.Culture.Wpf.csproj" Condition="'$(UseLocalCulture)' == 'true'" />
    <ProjectReference Include="..\..\src\Essential.Culture.Generator\Essential.Culture.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Condition="'$(UseLocalCulture)' == 'true'" />
  </ItemGroup>
</Project>
