<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ArkheideSystem.Essential.Culture</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Arkheide.Essential.Culture</PackageId>
    <Description>Strongly keyed, culture-aware JSON localization runtime.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\Essential.Culture.Generator\Essential.Culture.Generator.csproj"
      OutputItemType="Analyzer"
      ExcludeAssets="compile;runtime"
      Private="false"
      PrivateAssets="none" />
  </ItemGroup>

</Project>
