<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Arkheide.Essential.Culture.Test</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Arkheide.Essential.Culture\Arkheide.Essential.Culture.csproj" />
    <ProjectReference Include="..\..\src\Arkheide.Essential.Culture.Avalonia\Arkheide.Essential.Culture.Avalonia.csproj" />
    <ProjectReference Include="..\..\src\Arkheide.Essential.Culture.Wpf\Arkheide.Essential.Culture.Wpf.csproj" />
    <ProjectReference Include="..\..\src\Arkheide.Essential.Culture.Generator\Arkheide.Essential.Culture.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <AdditionalFiles Include="Culture.json" />
    <None Update="Culture.json" CopyToOutputDirectory="PreserveNewest" />
    <Using Include="System.IO" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
