<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <LangKeyNamespace>ArkheideSystem.LangKey.Demo.WpfApp.Generated</LangKeyNamespace>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\LangKey.json" Link="LangKey.json" />
    <None Include="..\LangKey.json" Link="LangKey.json" CopyToOutputDirectory="PreserveNewest" />
    <CompilerVisibleProperty Include="LangKeyNamespace" />
    <ProjectReference Include="..\..\src\LangKey.Wpf.Runtime\LangKey.Wpf.Runtime.csproj" />
    <ProjectReference Include="..\..\src\LangKey.Generator\LangKey.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
